export const textStyles = {
  heading: {
    fontFamily: 'heading',
    fontWeight: 'bold',
    color: 'header',
  },
  h1: {
    fontFamily: 'mono',
    fontWeight: '700',
    fontSize: { base: '5xl', md: '7xl' },
    color: 'text',
    lineHeight: '1.1',
    textWrap: 'balance',
  },
  h2: {
    fontFamily: 'heading',
    fontWeight: '700',
    fontSize: '5xl',
    color: 'header',
    lineHeight: '1.1',
    textWrap: 'balance',
    marginBottom: '4',
  },
  h3: {
    fontFamily: 'heading',
    fontWeight: '700',
    fontSize: '4xl',
    color: 'header',
    lineHeight: '1.2',
    textWrap: 'balance',
    marginBottom: '4',
  },
  h4: {
    fontFamily: 'heading',
    fontWeight: '700',
    fontSize: '3xl',
    color: 'header',
    lineHeight: '1.4',
    textWrap: 'balance',
  },
  h5: {
    fontFamily: 'heading',
    fontWeight: '700',
    fontSize: '2xl',
    color: 'header',
    lineHeight: '1.25',
    textWrap: 'balance',
  },
  'h2-mono': {
    fontFamily: 'mono',
    fontWeight: '700',
    fontSize: '5xl',
    color: 'header',
    lineHeight: '1.1',
    textWrap: 'balance',
  },
  'h3-mono': {
    fontFamily: 'mono',
    fontWeight: '700',
    fontSize: '4xl',
    color: 'header',
    lineHeight: '1.2',
    textWrap: 'balance',
  },
  'h4-mono': {
    fontFamily: 'mono',
    fontWeight: '700',
    fontSize: '3xl',
    color: 'header',
    lineHeight: '1.2',
    textWrap: 'balance',
  },
  'h5-mono': {
    fontFamily: 'mono',
    fontWeight: '700',
    fontSize: '2xl',
    color: 'header',
    lineHeight: '1.3',
    textWrap: 'balance',
  },
  'h6-mono': {
    fontFamily: 'mono',
    fontWeight: '700',
    fontSize: 'xl',
    color: 'header',
    lineHeight: '1.3',
    textWrap: 'balance',
  },
  body: {
    fontFamily: 'body',
    fontWeight: 'regular',
    fontSize: 'md',
    color: 'text',
  },
  link: {
    fontFamily: 'body',
    fontWeight: 'regular',
    fontSize: 'inherit',
    color: 'inherit',
  },
  code: {
    px: 1,
    py: 0.5,
    fontSize: '0.875em',
    fontFamily: 'mono',
    bg: 'mode',
    color: 'primary',
  },
}
